Removed comma-dangle rule
onebilltech/eslint-config-stealthone pull request #1
Opened 2017-02-16 17:55 UTC by srounce

Is there a good reason why this is explicitly set?

2017-02-16 18:10 UTC, colinclarkbcgdv requested changes

2017-02-16 18:10 UTC, colinclarkbcgdv commented on index.js
> -        'comma-dangle': ['error', 'never'],
because it overrides airbnb's rule that allows trailing commas.

2017-02-16 18:10 UTC, colinclarkbcgdv commented on index.js
> -        'comma-dangle': ['error', 'never'],
so we should probably keep that for now

2017-02-16 18:18 UTC, srounce commented on index.js
> -        'comma-dangle': ['error', 'never'],
Derp wrong rule.

2017-02-16 19:34 UTC, colinclarkbcgdv approved these changes
_cool, er, cool

2017-02-16 19:52 UTC, srounce commented
@zimbatm merge/permissions plz

2017-02-16 19:54 UTC, colinclarkbcgdv submitted a review, later dismissed
Wait, this allows underscores, so am removing the approval. https://github.com/airbnb/javascript/blob/8cab89e792e2fc457ab177cdf2d97e767e03ecb6/README.md#naming--leading-underscore

I think you should wait to get consensus on this PR before merging it.

2017-02-16 20:43 UTC, zimbatm commented
The Airbnb style guide kind of shoves the issue under the rug. The only other approach I know of is to hide private variables in a function scope. I'm not convinced this is a preferable solution though:

```js
function newCounter() {
  var counter = 0;
  return {
    incr: function() { counter += 1; },
    read: function() { return counter; } 
  };
}
```

2017-02-17 10:59 UTC, colinclarkbcgdv approved these changes
should not be blocked

2017-02-17 10:59 UTC, srounce commented
@eadz @jaiohanlon @jamieallen59 @rcambrj @martingBCG 
Do you have any input?

2017-02-17 13:38 UTC, srounce commented
@zimbatm I don't have permission to merge lol :)

2017-02-17 13:40 UTC, zimbatm commented
Permission from whom?

2017-02-17 13:40 UTC, srounce commented
"Need write access… blah"


> On 17 Feb 2017, at 13:40, zimbatm <notifications@github.com> wrote:
> 
> Permission from whom?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/onebilltech/eslint-config-stealthone/pull/1#issuecomment-280651800>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AADtePczl9bQmOvWrlFsuxWAR_6RVkNNks5rdaMzgaJpZM4MDV2Z>.
>

2017-02-17 13:41 UTC, zimbatm commented
Actually another option would be to introduce the `$` as a private prefix like you did in the wonderbill-api code.

2017-02-17 13:50 UTC, merged

2017-02-17 14:55 UTC, rcambrj commented
underscores have been used for private stuff in the extension since day one 

I know I'm late to the party, but :+1: